baseurl = "https://naelvis.github.io/refactored-happiness/"
publishDir = "docs"
languageCode = "en"
title = "refactored happiness"
author = "nelvis"
canonifyurls = true
paginate = 10
theme = "aether"

[params]
    brand = "r-h"
    description = "first and foremost: what's in the glass?"
    bgimg = "img/ignasi_pattern_s.png"

[markup]
  [markup.highlight]
    style = "igor"
