baseurl = "https://naelvis.github.io/refactored-happiness/"
publishDir = "docs"
languageCode = "en"
title = "refactored happiness"
author = "nelvis"
canonifyurls = true
paginate = 10
theme = "aether"
googleAnalytics = "UA-176386889-1"

[params]
    brand = "r-h"
    description = "my blog"
    homeimg = "img/boat_background.png"
    bgimg = "img/85.jpg"

[markup]
  [markup.highlight]
    style = "igor"
