baseurl = "https://naelvis.github.io/refactored-happiness/"
title = "Hugo Themes - aether"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
    brand = "aether"
    description = "aether Hugo theme for blogs"
    bgimg = "img/ignasi_pattern_s.png"

[markup]
  [markup.highlight]
    style = "igor"
